import fs from 'node:fs/promises'
import path from 'node:path'
import type { SeedMediaFile } from '../app/cms/seed-media'
import { parseRasterVariant } from '../app/services/responsiveImage'

const CONTENT_TYPES: Record<string, string> = {
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.png': 'image/png',
  '.webp': 'image/webp',
  '.gif': 'image/gif',
  '.svg': 'image/svg+xml'
}

/** Read `seed/media` as the seed media library: one entry per original, variants excluded. */
export async function readSeedMediaDir(seedDir: string): Promise<SeedMediaFile[]> {
  const entries = (await fs.readdir(seedDir)).filter((entry) => {
    const extension = path.extname(entry).toLowerCase()
    return CONTENT_TYPES[extension] != null && !parseRasterVariant(`/${entry}`)
  })

  const files: SeedMediaFile[] = []
  for (const filename of entries.sort()) {
    const stat = await fs.stat(path.join(seedDir, filename))
    files.push({
      key: filename,
      filename,
      contentType: CONTENT_TYPES[path.extname(filename).toLowerCase()],
      bytes: stat.size
    })
  }
  return files
}

/** Serialize the library as `app/cms/seed-media.ts` source. */
export function formatSeedMediaSource(files: SeedMediaFile[]): string {
  const lines = files.map(
    (file) =>
      `  { key: ${JSON.stringify(file.key)}, filename: ${JSON.stringify(file.filename)}, contentType: ${JSON.stringify(file.contentType)}, bytes: ${file.bytes} }`
  )

  return [
    '// Generated by `npm run cms:seed-media`. Edit files in seed/media, then re-run it.',
    'export type SeedMediaFile = {',
    '  key: string',
    '  filename: string',
    '  contentType: string',
    '  bytes: number',
    '}',
    '',
    'export const seedMediaFiles: SeedMediaFile[] = [',
    lines.join(',\n'),
    ']',
    ''
  ].join('\n')
}
